### ISSUE TITLE
IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by 456838** [YoKeyword/Fragmentation#568] opened 2017-09-23 02:55 UTC
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.duowan.onlyone, PID: 20887
                                                                    java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
                                                                        at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2044)
                                                                        at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2067)
                                                                        at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:680)
                                                                        at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:634)
                                                                        at me.yokeyword.fragmentation.TransactionDelegate.supportCommit(TransactionDelegate.java:268)
                                                                        at me.yokeyword.fragmentation.TransactionDelegate.start(TransactionDelegate.java:215)
                                                                        at me.yokeyword.fragmentation.TransactionDelegate.loadRootTransaction(TransactionDelegate.java:70)
                                                                        at me.yokeyword.fragmentation.SupportFragmentDelegate.loadRootFragment(SupportFragmentDelegate.java:376)
                                                                        at me.yokeyword.fragmentation.SupportFragmentDelegate.loadRootFragment(SupportFragmentDelegate.java:372)
                                                                        at me.yokeyword.fragmentation.SupportFragment.loadRootFragment(SupportFragment.java:276)
                                                                        at com.duowan.onlyone.fm.FirstFragment.onLazyInitView(FirstFragment.java:43)
                                                                        at me.yokeyword.fragmentation.helper.internal.VisibleDelegate.dispatchSupportVisible(VisibleDelegate.java:169)
                                                                        at me.yokeyword.fragmentation.helper.internal.VisibleDelegate.access$100(VisibleDelegate.java:19)
                                                                        at me.yokeyword.fragmentation.helper.internal.VisibleDelegate$1.run(VisibleDelegate.java:135)
                                                                        at android.os.Handler.handleCallback(Handler.java:754)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:163)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6315)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**it`s better to use commitAllowingStateLoss on BackStackRecord.**

**Comment by YoKeyword** [comment] 2017-09-24 09:12
Duplicate of #522

**Closed by YoKeyword** 2017-09-24 09:12 UTC
Labels: after onSaveInstanceState, duplicate
