### ISSUE TITLE
Fragment 在onDestroy调用 hideSoftInput() 内存泄漏

### ISSUE THREAD

**Issue by zwonb** [YoKeyword/Fragmentation#795] opened 2018-03-08 08:51 UTC
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by LonelyMushroom** [comment] 2018-03-08 08:52
是华为手机么?最好能贴log日志上来

**Comment by zwonb** [comment] 2018-03-08 08:52
Library version 1.2.6
Support-v4 version 27.0.2
Logs none
context 泄漏

**Comment by zwonb** [comment] 2018-03-08 08:56
[https://github.com/zwonb/RecyclerViewAdapter/blob/master/app/src/main/java/img/QQ%E6%88%AA%E5%9B%BE20180308165347.png](url)

**Comment by LonelyMushroom** [comment] 2018-03-08 08:57
这是源码实现,一般没什么问题,上线项目用了很久了
你上传的图片404
```
 public static void hideSoftInput(View view) {
        if (view == null || view.getContext() == null) return;
        InputMethodManager imm = (InputMethodManager) view.getContext().getSystemService(Context.INPUT_METHOD_SERVICE);
        imm.hideSoftInputFromWindow(view.getWindowToken(), 0);
    }
```

**Comment by zwonb** [comment] 2018-03-08 08:57
图片贴不到。。。

**Comment by zwonb** [comment] 2018-03-08 08:58
我不用库里面自带的那个方法了

**Comment by YoKeyword** [comment] 2018-03-08 10:24
Duplicate of #235

**Closed by YoKeyword** 2018-03-08 10:24 UTC
