### ISSUE TITLE
手势滑动返回后，如何监听当前Fragment或Activity页面是否被销毁

### ISSUE THREAD

**Issue by shaycormac** [YoKeyword/Fragmentation#914] opened 2018-06-25 08:22 UTC
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version 1.27
* Support-v4 version 27
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by YoKeyword** [comment] 2018-07-07 05:28
Duplicate of #735

**Closed by YoKeyword** 2018-07-07 05:28 UTC
Labels: duplicate
